### ISSUE TITLE
Request: Add option to copy to additional storage

### ISSUE THREAD

**Issue by myrison** [TheBestPessimist/duplicacy-utils#10]
Here is a suggested enhancement to make this useful in a wider set of circumstances:

- Add option to copy to second storage instead of just do a backup to a single storage
- Ideally, also add the ability to define a variable for which snapshot/repository you want to copy as opposed to forcing all of them to be done within one command (this way you can schedule copies at different times for different repositories if you don't want to do them all inside of one command)

Thanks!

**Comment by NiJoao** [comment]
The first bullet is addressed in pull request #11

**Comment by TheBestPessimist** [comment]
@myrison  can you explain a bit this:

> Ideally, also add the ability to define a variable for which snapshot/repository you want to copy as opposed to forcing all of them to be done within one command (this way you can schedule copies at different times for different repositories if you don't want to do them all inside of one command)

You mean you may have 3 different offsites, and you wanna chose what the source is and what the destination? That's not easily doable, and i don't want to go that path.

If you mean you wanna have a variable for just **a single offsite** `$offsiteName` then that's possible and will be added

**Comment by TheBestPessimist** [comment]
So what you want is to add a parameter for `-id` of the copy operation (ref: https://forum.duplicacy.com/t/copy-command-details/1083)

**Comment by myrison** [comment]
Yes, what I recall from when I wrote the original comment is that this wasn't configurable in the script.  Is it now?  Could be it has changed from when I first opened it.

**Comment by TheBestPessimist** [comment]
I've added this option now. Can you check it out?

You have to add the name of the snapshot to `$copySnapshotId`.
