### ISSUE TITLE
Filter - Exclude firefox/thunderbird places.sqlite

### ISSUE THREAD

**Issue by stompro** [TheBestPessimist/duplicacy-utils#19]
I've always found it useful to exclude the places.sqlite file from thunderbird/firefox to reduce churn.

That file stores browsing history and bookmarks, but bookmarks are automatically exported to seperate backup file every time the programs are closed, and I don't personally care about loosing my browsing history.

That file is created with a minimum size of 10MB, and always gets larger in increments of 10MB to reduce fragmentation of the database.  It gets updated every time a new page is loaded, so it will have changed for every backup.  Since it is a database file, with indexes and data being updated in different placed of the file, I doubt that the dedup handles it very well.  But I don't know that for a fact.

It may be worth adding that as an optional exclude setting in the Thunderbird/Firefox sections.

Something like

e:(?i)/AppData/Roaming/(Mozilla/Firefox|Thunderbird)/Profiles/[^/]+/places.sqlite.*

Also, I don't think the AppData/(Local|LocalLow)/(Mozilla|Thunderbird)/ folders need to be backed up either.

Josh

**Comment by mr-flibble** [comment]
You may also want exclude \Data\profile\global-messages-db.sqlite  - its search index for TB and if deleted - its automatically recreated. And it can have size in couple of GB

**Comment by TheBestPessimist** [comment]
About `places.sqlite`: isn't this file used for storing browsing history and whatnot?
In that case i wouldn't want to exclude it just because some people (_me_) do search a lot through their history and not having it after a restore would kinda piss me off.

references: 
http://kb.mozillazine.org/Bookmarks_history_and_toolbar_buttons_not_working_-_Firefox

**Comment by TheBestPessimist** [comment]
Any input here, guys?

**Comment by TheBestPessimist** [comment]
As per the discussion on the forum (https://forum.duplicacy.com/t/filters-file-should-i-exclude-thunderbird-imapmail-folder/1475) i think i won't do anything regarding the thunderbird file. 

If you want to discuss a bit more about this, we can do it on the forum.
