### ISSUE TITLE
telegram error

### ISSUE THREAD

**Issue by anibalinbalin** [TheBestPessimist/duplicacy-utils#22]
Hi! I just edited the user_config to my basic needs and got an error when this goes:
`PS C:\Users\Post\Desktop\duplicacy-utils-master> .\backup.ps1
2019-01-23 10:49:23.239
2019-01-23 10:49:23.246
2019-01-23 10:49:23.249 =================================================================
2019-01-23 10:49:23.252 ==== Starting Duplicacy Backup @ C:\Users\Post\Desktop
2019-01-23 10:49:23.254 ====
2019-01-23 10:49:23.257 ==== Start time is: 2019-01-23 10:49:23
2019-01-23 10:49:23.259 =================================================================
2019-01-23 10:49:23.261 === doRemoteNotifications
2019-01-23 10:49:23.263 === doTelegramNotification
Invoke-WebRequest : status: error ({Ok:false ErrorCode:400 Description:Bad Request: chat not found})
At C:\Users\Post\Desktop\duplicacy-utils-master\remote_notifications_util.ps1:72 char:9
+         Invoke-WebRequest `
+         ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`

So I decided to take a look at remote_notifications_util and found that I would need to address a chat id and token. So I made a bot, I got the needed data but I'm not sure where should I add it since it is declared: chat_id = $telegramToken

Thanks for your help.

**Comment by TheBestPessimist** [comment]
> So I made a bot

What bot did you create? I already created the telegram bot: https://t.me/DuplicacyUtilsTBPBot, and this is the one everybody should use.

> and found that I would need to address a chat id and token

Ah, this is my fault, there should have been a check there: if there is any `$telegramToken` only then try and do a notification.

**Comment by TheBestPessimist** [comment]
Please update (just do a normal git pull) and now the error should be fixed. (also: use my telegram bot and give feedback!)
