### ISSUE TITLE
526 error(Invalid SSL certificate) on remote_notification_util.ps1

### ISSUE THREAD

**Issue by stanly0726** [TheBestPessimist/duplicacy-utils#33]
as title imply your certificate is out of date
maybe modify the code so that a relay server won't be needed?

**Comment by TheBestPessimist** [comment]
Thank you for the ping. it works now. Unfortunately, this will keep happening as i cannot make [linuxserver swag](https://github.com/linuxserver/docker-swag) to automatically renew the certs. It never worked for me.
