### ISSUE TITLE
Mac OS/X Utilities for using/utilizing Duplicacy 

### ISSUE THREAD

**Issue by jeffaco** [TheBestPessimist/duplicacy-utils#5]
Howdy.

I'm looking to write a series of scripts (and instructions) to utilize Duplicacy on Mac OS/X. The question: Where to put it? It will be a "full implementation" (something that somebody could clone directly, add configuration files, and run as is after configuration files are created).

I can create my own repo and add it to the [Duplicacy CLI Wiki][], or I can do it here. If I did it here, though, the entire repo would need to be reorganized. My thoughts, if you're interested:

1. Add `windows` subdirectory, move most files there (except for common `filters` file, I guess, unless we wanted to split filters between `macintosh` directory and `windows` directory so it's no longer common),
2. Have a Windows-specific README.md in the `windows` directory (pretty much your existing one),
3. Create a new README.md at base explaining different directory structure,
4. Create a new `macintosh` directory, do my work there.
5. Preferably get direct commit access so I don't have to work with a fork and do PRs requiring your assistance even though you don't appear to use Mac OS/X.

Or, if you're not really interested, I can just create my own repo and refer to it in the [Duplicacy CLI Wiki][].

What are your feelings on this? I'm happy to start with a PR for the reorganization. Thanks!

[Duplicacy CLI Wiki]: https://github.com/gilbertchen/duplicacy/wiki/Scripts-and-utilities-index

**Comment by jeffaco** [comment]
On second thought, it probably makes sense to just make my own repo and post to the Wiki. It's really completely independent from what you're doing.

Thanks anyway.

**Comment by TheBestPessimist** [comment]
well... you;re welcome.. i guess :D
