### ISSUE TITLE
Request: Add variable for upload speed

### ISSUE THREAD

**Issue by myrison** [TheBestPessimist/duplicacy-utils#9]
Here is a suggested enhancement to make this useful in a wider set of circumstances:

- Add variable to set upload speed in the config file

**Comment by TheBestPessimist** [comment]
upload speed for the backup and copy commands?

**Comment by myrison** [comment]
Yep, sorry that wasn't clear, as an example:
duplicacy -log  copy -id {snapshot-id} -to {storage} -threads {threads} -upload-limit-rate {kBps}

**Comment by NiJoao** [comment]
This was addressed in pull request #11 .
Only tested by me, and not extensively, so please do be careful
